[build]
  publish = "exampleSite/public"
  functions = "functions"
  command = "hugo -s exampleSite --gc --minify --themesDir ../.. -b $HUGO_BASEURL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	debug = false

[template.environment]
  HUGO_BASEURL = "https://yourdomain.com"
  PAYMONGO_EMAIL = "Paymongo Email"
  PAYMONGO_PASS = "Paymongo Password"
  PAYMONGO_LIVEMODE = "set to true on live site"

[build.environment]
  HUGO_VERSION = "0.75.1"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  environment = { HUGO_THEME = "repo" }

[context.deploy-preview]
  command = "hugo -s exampleSite --gc --minify --themesDir ../.. -b $DEPLOY_PRIME_URL --buildFuture"
